version: '3.8'

services:

  database:
    image: "postgres:16"
    container_name: postgres
    restart: always

    environment:
      # новопточники сказали как-то по другому передавать пароль
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: zookeeper
      PGDATA: /var/lib/postgresql/data/pgdata

    ports:
      - "5432:5432"

#  app:
#    container_name: restaurant-delivary
#    restart: always
#
#    build:
#      context: ./
#      dockerfile: Dockerfile
#
#    environment:
#      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/restaurant-delivary
#
#    ports:
#      - "8080:8080"
#    depends_on:
#      - database
