version: '3'

services:

  database:
    image: "postgres:16-alpine"
    container_name: postgres
    restart: always

    environment:
      # новопточники сказали как-то по другому передавать пароль
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: restaurant-delivery
      PGDATA: /var/lib/postgresql/data/pgdata

    ports:
      - "5432:5432"

#  sonarqube:
#    image: "sonarqube:community"
#    container_name: sonarqube
#    restart: always
#
#    environment:
#      SONAR_JDBC_URL: jdbc:postgresql://postgres:5432/sonar
#      SONAR_JDBC_USERNAME: sonar
#      SONAR_JDBC_PASSWORD: sonar
#
#    ports:
#      - "9000:9000"
#
#    depends_on:
#      - database

  app:
    container_name: restaurant-delivery
    restart: always

    build:
      context: ./
      dockerfile: Dockerfile

    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/restaurant-delivery

    ports:
      - "8080:8080"
    depends_on:
      - database
