name: Deploy to Hosting
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Deploy to Hosting
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST_SERVER }}
          username: ${{ secrets.HOST_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd restaurant-delivery-api/restaurant-delivery-api/
            git pull
            ./gradlew clean build -x test
            docker-compose build
            docker-compose up -d

            cd front
            npm run dev
